name: Dependency Check (Manual)

on:
  workflow_dispatch:

jobs:
 scan:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: package.json
        path: C:\Users\north\Documents\GIT CODE\extra-assignment-1-AamirRahman11
        format: HTML

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-report
        path: reports
